this.title=
contCreator.boundLabelText=\u521B\u5EFA\u8005
contCreateTime.boundLabelText=\u521B\u5EFA\u65F6\u95F4
contNumber.boundLabelText=\u5355\u636E\u7F16\u53F7
contAuditor.boundLabelText=\u5BA1\u6838\u4EBA
contAuditTime.boundLabelText=\u5BA1\u6279\u65F6\u95F4
contPurpose.boundLabelText=\u91C7\u8D2D\u7528\u9014
contApplyPurpose.boundLabelText=\u91C7\u8D2D\u7528\u9014
contApplyDept.boundLabelText=\u9700\u6C42\u90E8\u95E8
contApplyPerson.boundLabelText=\u8D23\u4EFB\u4EBA
contDept.boundLabelText=\u9700\u6C42\u90E8\u95E8
contPerson.boundLabelText=\u8D23\u4EFB\u4EBA
contContractWFType.boundLabelText=\u91C7\u8D2D\u65B9\u5F0F
ActionSubmit.SHORT_DESCRIPTION=
ActionSubmit.LONG_DESCRIPTION=
ActionSubmit.NAME=