this.title=\u62DB\u6807\u6587\u4EF6\u7F16\u8F91\u754C\u9762
contCreator.boundLabelText=\u5236\u5355\u4EBA
contCreateTime.boundLabelText=\u5236\u5355\u65E5\u671F
contNumber.boundLabelText=\u5355\u636E\u7F16\u53F7
contAuditor.boundLabelText=\u5BA1\u6279\u4EBA
contName.boundLabelText=\u91C7\u8D2D\u5185\u5BB9
contAuditTime.boundLabelText=\u5BA1\u6279\u65E5\u671F
contInviteType.boundLabelText=\u91C7\u8D2D\u7C7B\u522B
contPurchaseMode.boundLabelText=\u91C7\u8D2D\u65B9\u5F0F
contNeedDept.boundLabelText=\u9700\u6C42\u90E8\u95E8
contRespPerson.boundLabelText=\u8D23\u4EFB\u4EBA
contPurpose.boundLabelText=\u62DB\u6807\u6587\u4EF6\u5185\u5BB9
contAttachment.title=\u9644\u4EF6\u7BA1\u7406
tblAttachement.seq=\u9644\u4EF6\u7F16\u7801
tblAttachement.name=\u9644\u4EF6\u540D\u79F0
tblAttachement.type=\u7C7B\u578B
tblAttachement.date=\u4E0A\u4F20\u65E5\u671F
tblAttachement.id=id
tblAttachement.formatXml=<?xml version\="1.0" encoding\="UTF-8"?><DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles><c\:Style id\="sTable"><c\:Alignment horizontal\="left" /><c\:Protection locked\="true" /></c\:Style><c\:Style id\="sCol0"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol2"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol3"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol4"><c\:Protection hidden\="true" /></c\:Style></Styles><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="2" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100" t\:styleID\="sTable"><t\:ColumnGroup><t\:Column t\:key\="seq" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="-1" t\:styleID\="sCol0" /><t\:Column t\:key\="name" t\:width\="400" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="1" /><t\:Column t\:key\="type" t\:width\="80" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="2" t\:styleID\="sCol2" /><t\:Column t\:key\="date" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="3" t\:styleID\="sCol3" /><t\:Column t\:key\="id" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="4" t\:styleID\="sCol4" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header1" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>\u9644\u4EF6\u7F16\u7801</t\:Cell><t\:Cell>\u9644\u4EF6\u540D\u79F0</t\:Cell><t\:Cell>\u7C7B\u578B</t\:Cell><t\:Cell>\u4E0A\u4F20\u65E5\u671F</t\:Cell><t\:Cell>id</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot>
contProj.boundLabelText=\u5DE5\u7A0B\u9879\u76EE
contOrg.boundLabelText=\u7EC4\u7EC7
contBizDate.boundLabelText=\u7533\u8BF7\u65E5\u671F
contBelong.boundLabelText=\u91C7\u8D2D\u5F52\u5C5E
cbBelong.items=[Enum]com.kingdee.eas.fdc.contract.PurchaseBelongEnum
contAmount.boundLabelText=\u9884\u7B97\u91D1\u989D
contAmountBig.boundLabelText=\u5927\u5199\u91D1\u989D
contPurchaseType.boundLabelText=\u91C7\u8D2D\u65B9\u5F0F
cbPurchaseType.items=[Enum]com.kingdee.eas.fdc.contract.PurchaseTypeEnum
ActionSubmit.SHORT_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.LONG_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.NAME=\u63D0\u4EA4