this.title=
mainPanel.constraints=\u5408\u540C\u57FA\u672C\u4FE1\u606F
contractPropert.items=[Enum]com.kingdee.eas.fdc.contract.ContractPropertyEnum
pnlInviteInfo.constraints=\u62DB\u6807/\u8BAE\u6807/\u6218\u7565\u5408\u4F5C\u4FE1\u606F
comboCoopLevel.items=[Enum]com.kingdee.eas.fdc.contract.CoopLevelEnum
comboPriceType.items=[Enum]com.kingdee.eas.fdc.contract.PriceTypeEnum
pnlDetail.constraints=\u5408\u540C\u8BE6\u7EC6\u4FE1\u606F
pnlCost.constraints=\u6210\u672C\u4FE1\u606F
panelInvite.constraints=\u62DB\u6807\u4FE1\u606F
kdtSupplyEntry.constraints=\u8865\u5145\u5408\u540C\u4FE1\u606F
kDContainer3.constraints=\u5408\u540C\u7B7E\u8BA2\u660E\u7EC6
kDContainer4.constraints=\u8425\u9500\u5408\u540C\u5206\u644A\u660E\u7EC6
kDContainer5.constraints=\u5370\u7AE0\u4FE1\u606F
kDContainer6.constraints=\u591A\u7532\u65B9\u7B7E\u8BA2\u660E\u7EC6
costProperty.items=[Enum]com.kingdee.eas.fdc.contract.CostPropertyEnum
ecoItemPanel.constraints=\u5408\u540C\u7ECF\u6D4E\u6761\u6B3E
btnSubmit.text=
btnSubmit.toolTipText=
btnAudit.text=
btnAudit.toolTipText=
menuItemSubmit.text=
menuItemAudit.text=
menuItemAudit.toolTipText=
menuItemUnAudit.text=
menuItemUnAudit.toolTipText=
ActionSubmit.SHORT_DESCRIPTION=
ActionSubmit.LONG_DESCRIPTION=
ActionSubmit.NAME=
ActionPrint.SHORT_DESCRIPTION=
ActionPrint.LONG_DESCRIPTION=
ActionPrint.NAME=
ActionPrintPreview.SHORT_DESCRIPTION=
ActionPrintPreview.LONG_DESCRIPTION=
ActionPrintPreview.NAME=
ActionAudit.SHORT_DESCRIPTION=
ActionAudit.LONG_DESCRIPTION=
ActionAudit.NAME=
ActionUnAudit.SHORT_DESCRIPTION=
ActionUnAudit.LONG_DESCRIPTION=
ActionUnAudit.NAME=
ActionSplit.SHORT_DESCRIPTION=
ActionSplit.LONG_DESCRIPTION=
ActionSplit.NAME=
ActionViewContent.SHORT_DESCRIPTION=
ActionViewContent.LONG_DESCRIPTION=
ActionViewContent.NAME=
ActionContractPlan.SHORT_DESCRIPTION=
ActionContractPlan.LONG_DESCRIPTION=
ActionContractPlan.NAME=
ActionDelSplit.SHORT_DESCRIPTION=
ActionDelSplit.LONG_DESCRIPTION=
ActionDelSplit.NAME=
ActionViewCost.SHORT_DESCRIPTION=
ActionViewCost.LONG_DESCRIPTION=
ActionViewCost.NAME=
ActionViewBgBalance.SHORT_DESCRIPTION=
ActionViewBgBalance.LONG_DESCRIPTION=
ActionViewBgBalance.NAME=
ActionViewAttachmentSelf.SHORT_DESCRIPTION=
ActionViewAttachmentSelf.LONG_DESCRIPTION=
ActionViewAttachmentSelf.NAME=
ActionViewContentSelf.SHORT_DESCRIPTION=
ActionViewContentSelf.LONG_DESCRIPTION=
ActionViewContentSelf.NAME=
ActionProgram.SHORT_DESCRIPTION=
ActionProgram.LONG_DESCRIPTION=
ActionProgram.NAME=
ActionViewProgramCon.SHORT_DESCRIPTION=
ActionViewProgramCon.LONG_DESCRIPTION=
ActionViewProgramCon.NAME=
ActionAgreementText.SHORT_DESCRIPTION=
ActionAgreementText.LONG_DESCRIPTION=
ActionAgreementText.NAME=
ActionUpLoad.SHORT_DESCRIPTION=
ActionUpLoad.LONG_DESCRIPTION=
ActionUpLoad.NAME=
ActionDownLoad.SHORT_DESCRIPTION=
ActionDownLoad.LONG_DESCRIPTION=
ActionDownLoad.NAME=
ActionAccountView.SHORT_DESCRIPTION=
ActionAccountView.LONG_DESCRIPTION=
ActionAccountView.NAME=
ActionDetailALine.SHORT_DESCRIPTION=
ActionDetailALine.LONG_DESCRIPTION=
ActionDetailALine.NAME=
ActionDetailILine.SHORT_DESCRIPTION=
ActionDetailILine.LONG_DESCRIPTION=
ActionDetailILine.NAME=
ActionDetailRLine.SHORT_DESCRIPTION=
ActionDetailRLine.LONG_DESCRIPTION=
ActionDetailRLine.NAME=
ActionMALine.SHORT_DESCRIPTION=
ActionMALine.LONG_DESCRIPTION=
ActionMALine.NAME=
ActionMRLine.SHORT_DESCRIPTION=
ActionMRLine.LONG_DESCRIPTION=
ActionMRLine.NAME=
ActionYZALine.SHORT_DESCRIPTION=
ActionYZALine.LONG_DESCRIPTION=
ActionYZALine.NAME=
ActionYZRLine.SHORT_DESCRIPTION=
ActionYZRLine.LONG_DESCRIPTION=
ActionYZRLine.NAME=
ActionMDALine.SHORT_DESCRIPTION=
ActionMDALine.LONG_DESCRIPTION=
ActionMDALine.NAME=
ActionMDRLine.SHORT_DESCRIPTION=
ActionMDRLine.LONG_DESCRIPTION=
ActionMDRLine.NAME=