this.title=\u79DF\u8CC3\u5408\u540C\u5E8F\u4E8B\u7C3F
tblMain.id=ID
tblMain.tenancyState=\u5408\u540C\u72C0\u614B
tblMain.moreRoomsType=\u591A\u623F\u7522\u8A08\u7B97\u65B9\u5F0F
tblMain.auditDate=\u5BE9\u6279\u65E5\u671F
tblMain.number=\u5408\u540C\u7DE8\u78BC
tblMain.tenancyName=\u5408\u540C\u540D\u7A31
tblMain.tenRoomsDes=\u51FA\u79DF\u623F\u9593
tblMain.buildingArea=\u8A08\u79DF\u9762\u7A4D
tblMain.tenAttachesDes=\u914D\u5957\u8CC7\u6E90
tblMain.tenBillRoomState=\u623F\u6E90\u72C0\u614B
tblMain.tenCustomerDes=\u5BA2\u6236
tblMain.brandDesc=\u54C1\u724C
tblMain.tenancyType=\u5408\u540C\u985E\u578B
tblMain.oldTenancyBill.tenancyName=\u539F\u5408\u540C
tblMain.startDate=\u958B\u59CB\u65E5\u671F
tblMain.leaseCount=\u79DF\u671F
tblMain.endDate=\u7D50\u675F\u65E5\u671F
tblMain.quitRoomDate=\u9000\u79DF\u65E5\u671F
tblMain.leaseTime=\u8A08\u79DF\u671F\u9593\u9577\u5EA6
tblMain.flagAtTerm=\u5230\u671F\u6A19\u8A18
tblMain.tenancyAdviser.name=\u79DF\u8CC3\u9867\u554F
tblMain.agency.name=\u4EE3\u7406\u5546
tblMain.dealTotalRent=\u6210\u4EA4\u79DF\u91D1
tblMain.roomsRentType=\u623F\u9593\u8A18\u79DF\u9031\u671F
tblMain.standardTotalRent=\u6A19\u6E96\u79DF\u91D1
tblMain.depositAmount=\u62BC\u91D1
tblMain.firstPayRent=\u9996\u4ED8\u79DF\u91D1
tblMain.deliveryRoomDate=\u7D04\u5B9A\u4EA4\u623F\u65E5\u671F
tblMain.description=\u5099\u8A3B
tblMain.specialClause=\u7279\u6B8A\u689D\u6B3E
tblMain.creator.name=\u5236\u55AE\u4EBA
tblMain.createTime=\u5236\u55AE\u65E5\u671F
tblMain.state=\u55AE\u64DA\u72C0\u614B
tblMain.submitDate=\u63D0\u4EA4\u65E5\u671F
tblMain.isUpdateXHTenancyBill=\u662F\u5426\u66F4\u65B0\u661F\u701A\u5408\u540C
tblMain.owedAmount=\u7D42\u6B62\u5408\u540C\u79DF\u91D1\u6B20\u8CBB
tblMain.owedWYAmount=\u7D42\u6B62\u5408\u540C\u7269\u696D\u8CBB\u6B20\u8CBB
tblMain.owedSFAmount=\u7D42\u6B62\u5408\u540C\u6C34\u8CBB\u6B20\u8CBB
tblMain.owedDFAmount=\u7D42\u6B62\u5408\u540C\u96FB\u8CBB\u6B20\u8CBB
tblMain.owedJYAmount=\u7D42\u6B62\u5408\u540C\u7D93\u71DF\u79DF\u8CC3\u8CBB\u6B20\u8CBB
tblMain.xhCustomerNum=\u661F\u701A\u5BA2\u6236\u7DE8\u78BC
tblMain.xhCustomer=\u661F\u701A\u5BA2\u6236
tblMain.xhRoomArea=\u661F\u701A\u623F\u6E90\u9762\u7A4D
tblMain.sysCustomerNum=\u4E3B\u6578\u64DA\u5BA2\u6236\u7DE8\u78BC
tblMain.sysCustomer=\u4E3B\u6578\u64DA\u5BA2\u6236
tblMain.formatXml=<?xml version\="1.0" encoding\="UTF-8"?><DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles><c\:Style id\="sCol0"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol2"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol8"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol19"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol21"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol23"><c\:Protection hidden\="true" /></c\:Style><c\:Style id\="sCol32"><c\:Protection hidden\="true" /></c\:Style></Styles><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="15" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100"><t\:ColumnGroup><t\:Column t\:key\="id" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="0" t\:styleID\="sCol0" /><t\:Column t\:key\="tenancyState" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="1" /><t\:Column t\:key\="moreRoomsType" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="2" t\:styleID\="sCol2" /><t\:Column t\:key\="auditDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="3" /><t\:Column t\:key\="number" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="4" /><t\:Column t\:key\="tenancyName" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="5" /><t\:Column t\:key\="tenRoomsDes" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="6" /><t\:Column t\:key\="buildingArea" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="7" /><t\:Column t\:key\="tenAttachesDes" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="8" t\:styleID\="sCol8" /><t\:Column t\:key\="tenBillRoomState" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="9" /><t\:Column t\:key\="tenCustomerDes" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="10" /><t\:Column t\:key\="brandDesc" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="11" /><t\:Column t\:key\="tenancyType" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="12" /><t\:Column t\:key\="oldTenancyBill.tenancyName" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="13" /><t\:Column t\:key\="startDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="14" /><t\:Column t\:key\="leaseCount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="15" /><t\:Column t\:key\="endDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="16" /><t\:Column t\:key\="quitRoomDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="17" /><t\:Column t\:key\="leaseTime" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="18" /><t\:Column t\:key\="flagAtTerm" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="19" t\:styleID\="sCol19" /><t\:Column t\:key\="tenancyAdviser.name" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="20" /><t\:Column t\:key\="agency.name" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="21" t\:styleID\="sCol21" /><t\:Column t\:key\="dealTotalRent" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="22" /><t\:Column t\:key\="roomsRentType" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="23" t\:styleID\="sCol23" /><t\:Column t\:key\="standardTotalRent" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="24" /><t\:Column t\:key\="depositAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="25" /><t\:Column t\:key\="firstPayRent" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="26" /><t\:Column t\:key\="deliveryRoomDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="27" /><t\:Column t\:key\="description" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="28" /><t\:Column t\:key\="specialClause" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="29" /><t\:Column t\:key\="creator.name" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="30" /><t\:Column t\:key\="createTime" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="31" /><t\:Column t\:key\="state" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="32" t\:styleID\="sCol32" /><t\:Column t\:key\="submitDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="33" /><t\:Column t\:key\="isUpdateXHTenancyBill" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="-1" /><t\:Column t\:key\="owedAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="-1" /><t\:Column t\:key\="owedWYAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="36" /><t\:Column t\:key\="owedSFAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="37" /><t\:Column t\:key\="owedDFAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="38" /><t\:Column t\:key\="owedJYAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="39" /><t\:Column t\:key\="xhCustomerNum" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="40" /><t\:Column t\:key\="xhCustomer" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="41" /><t\:Column t\:key\="xhRoomArea" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="42" /><t\:Column t\:key\="sysCustomerNum" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="-1" /><t\:Column t\:key\="sysCustomer" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="-1" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>ID</t\:Cell><t\:Cell>\u5408\u540C\u72C0\u614B</t\:Cell><t\:Cell>\u591A\u623F\u7522\u8A08\u7B97\u65B9\u5F0F</t\:Cell><t\:Cell>\u5BE9\u6279\u65E5\u671F</t\:Cell><t\:Cell>\u5408\u540C\u7DE8\u78BC</t\:Cell><t\:Cell>\u5408\u540C\u540D\u7A31</t\:Cell><t\:Cell>\u51FA\u79DF\u623F\u9593</t\:Cell><t\:Cell>\u8A08\u79DF\u9762\u7A4D</t\:Cell><t\:Cell>\u914D\u5957\u8CC7\u6E90</t\:Cell><t\:Cell>\u623F\u6E90\u72C0\u614B</t\:Cell><t\:Cell>\u5BA2\u6236</t\:Cell><t\:Cell>\u54C1\u724C</t\:Cell><t\:Cell>\u5408\u540C\u985E\u578B</t\:Cell><t\:Cell>\u539F\u5408\u540C</t\:Cell><t\:Cell>\u958B\u59CB\u65E5\u671F</t\:Cell><t\:Cell>\u79DF\u671F</t\:Cell><t\:Cell>\u7D50\u675F\u65E5\u671F</t\:Cell><t\:Cell>\u9000\u79DF\u65E5\u671F</t\:Cell><t\:Cell>\u8A08\u79DF\u671F\u9593\u9577\u5EA6</t\:Cell><t\:Cell>\u5230\u671F\u6A19\u8A18</t\:Cell><t\:Cell>\u79DF\u8CC3\u9867\u554F</t\:Cell><t\:Cell>\u4EE3\u7406\u5546</t\:Cell><t\:Cell>\u6210\u4EA4\u79DF\u91D1</t\:Cell><t\:Cell>\u623F\u9593\u8A18\u79DF\u9031\u671F</t\:Cell><t\:Cell>\u6A19\u6E96\u79DF\u91D1</t\:Cell><t\:Cell>\u62BC\u91D1</t\:Cell><t\:Cell>\u9996\u4ED8\u79DF\u91D1</t\:Cell><t\:Cell>\u7D04\u5B9A\u4EA4\u623F\u65E5\u671F</t\:Cell><t\:Cell>\u5099\u8A3B</t\:Cell><t\:Cell>\u7279\u6B8A\u689D\u6B3E</t\:Cell><t\:Cell>\u5236\u55AE\u4EBA</t\:Cell><t\:Cell>\u5236\u55AE\u65E5\u671F</t\:Cell><t\:Cell>\u55AE\u64DA\u72C0\u614B</t\:Cell><t\:Cell>\u63D0\u4EA4\u65E5\u671F</t\:Cell><t\:Cell>\u662F\u5426\u66F4\u65B0\u661F\u701A\u5408\u540C</t\:Cell><t\:Cell>\u7D42\u6B62\u5408\u540C\u79DF\u91D1\u6B20\u8CBB</t\:Cell><t\:Cell>\u7D42\u6B62\u5408\u540C\u7269\u696D\u8CBB\u6B20\u8CBB</t\:Cell><t\:Cell>\u7D42\u6B62\u5408\u540C\u6C34\u8CBB\u6B20\u8CBB</t\:Cell><t\:Cell>\u7D42\u6B62\u5408\u540C\u96FB\u8CBB\u6B20\u8CBB</t\:Cell><t\:Cell>\u7D42\u6B62\u5408\u540C\u7D93\u71DF\u79DF\u8CC3\u8CBB\u6B20\u8CBB</t\:Cell><t\:Cell>\u661F\u701A\u5BA2\u6236\u7DE8\u78BC</t\:Cell><t\:Cell>\u661F\u701A\u5BA2\u6236</t\:Cell><t\:Cell>\u661F\u701A\u623F\u6E90\u9762\u7A4D</t\:Cell><t\:Cell>\u4E3B\u6578\u64DA\u5BA2\u6236\u7DE8\u78BC</t\:Cell><t\:Cell>\u4E3B\u6578\u64DA\u5BA2\u6236</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot>
btnAudit.text=\u5BE9\u6279
btnAudit.toolTipText=\u5BE9\u6279
btnUnAudit.text=\u53CD\u5BE9\u6279
btnUnAudit.toolTipText=\u53CD\u5BE9\u6279
btnBlankOut.text=\u4F5C\u5EE2
btnBlankOut.toolTipText=\u4F5C\u5EE2
btnHandleTenancy.text=\u623F\u9593\u4EA4\u63A5
btnHandleTenancy.toolTipText=\u623F\u9593\u4EA4\u63A5
btnReceiveBill.text=\u6536\u6B3E
btnReceiveBill.toolTipText=\u6536\u6B3E
btnRefundment.text=\u9000\u6B3E
btnRefundment.toolTipText=\u9000\u6B3E
btnCarryForward.text=\u62BC\u91D1\u7D50\u8F49
btnCarryForward.toolTipText=\u62BC\u91D1\u7D50\u8F49
btnFlagAtTerm.text=\u5230\u671F\u6A19\u8A18
btnFlagAtTerm.toolTipText=\u5230\u671F\u6A19\u8A18
btnSpecial.text=\u7279\u6B8A\u6D41\u7A0B
btnSpecial.toolTipText=\u7279\u6B8A\u6D41\u7A0B
btnRepairStartDate.text=\u88DC\u9304\u79DF\u8CC3\u958B\u59CB\u65E5\u671F
btnPrintBill.text=\u79DF\u8CC3\u5408\u540C\u5957\u6253
btnPrintPreviewBill.text=\u79DF\u8CC3\u5408\u540C\u5957\u6253\u9810\u89BD
kDWorkButton1.text=\u5408\u540C\u5C0E\u5165
kDWorkButton2.text=\u4FEE\u5FA9\u5C0E\u5165\u5408\u540C
menuItemAudit.text=\u5BE9\u6279
menuItemAudit.toolTipText=\u5BE9\u6279
menuItemUnAudit.text=\u53CD\u5BE9\u6279
menuItemUnAudit.toolTipText=\u53CD\u5BE9\u6279
menuItemBlankOut.text=\u4F5C\u5EE2
menuItemBlankOut.toolTipText=\u4F5C\u5EE2
menuItemHandleTenancy.text=\u623F\u9593\u4EA4\u63A5
menuItemHandleTenancy.toolTipText=\u623F\u9593\u4EA4\u63A5
menuItemReceiveBill.text=\u6536\u6B3E
menuItemReceiveBill.toolTipText=\u6536\u6B3E
menuItemRefundment.text=\u9000\u6B3E
menuItemRefundment.toolTipText=\u9000\u6B3E
menuItemCarryForward.text=\u62BC\u91D1\u7D50\u8F49
menuItemCarryForward.toolTipText=\u62BC\u91D1\u7D50\u8F49
menuItemFlagAtTerm.text=\u5230\u671F\u6A19\u8A18
menuItemFlagAtTerm.toolTipText=\u5230\u671F\u6A19\u8A18
menuSpecial.text=\u7279\u6B8A\u696D\u52D9
menuSpecial.toolTipText=\u7279\u6B8A\u696D\u52D9
menuItemContinueTenancy.text=\u7E8C\u79DF\u7533\u8ACB
menuItemContinueTenancy.toolTipText=\u7E8C\u79DF\u7533\u8ACB
menuItemRejiggerTenancy.text=\u6539\u79DF\u7533\u8ACB
menuItemRejiggerTenancy.toolTipText=\u6539\u79DF\u7533\u8ACB
menuItemChangeName.text=\u8F49\u540D\u7533\u8ACB
menuItemChangeName.toolTipText=\u8F49\u540D\u7533\u8ACB
menuItemQuitTenancy.text=\u9000\u79DF\u7533\u8ACB
menuItemQuitTenancy.toolTipText=\u9000\u79DF\u7533\u8ACB
menuRepairStartDate.text=\u88DC\u9304\u79DF\u8CC3\u958B\u59CB\u65E5\u671F
ActionContinueTenancy.SHORT_DESCRIPTION=
ActionContinueTenancy.LONG_DESCRIPTION=
ActionContinueTenancy.NAME=
ActionRejiggerTenancy.SHORT_DESCRIPTION=
ActionRejiggerTenancy.LONG_DESCRIPTION=
ActionRejiggerTenancy.NAME=
ActionChangeName.SHORT_DESCRIPTION=
ActionChangeName.LONG_DESCRIPTION=
ActionChangeName.NAME=
ActionAudit.SHORT_DESCRIPTION=\u5BE9\u6279
ActionAudit.LONG_DESCRIPTION=\u5BE9\u6279
ActionAudit.NAME=\u5BE9\u6279
ActionUnAudit.SHORT_DESCRIPTION=
ActionUnAudit.LONG_DESCRIPTION=
ActionUnAudit.NAME=
ActionBlankOut.SHORT_DESCRIPTION=
ActionBlankOut.LONG_DESCRIPTION=
ActionBlankOut.NAME=
ActionQuitTenancy.SHORT_DESCRIPTION=
ActionQuitTenancy.LONG_DESCRIPTION=
ActionQuitTenancy.NAME=
ActionHandleTenancy.SHORT_DESCRIPTION=
ActionHandleTenancy.LONG_DESCRIPTION=
ActionHandleTenancy.NAME=
ActionReceiveBill.SHORT_DESCRIPTION=
ActionReceiveBill.LONG_DESCRIPTION=
ActionReceiveBill.NAME=
ActionRefundment.SHORT_DESCRIPTION=
ActionRefundment.LONG_DESCRIPTION=
ActionRefundment.NAME=
ActionCarryForward.SHORT_DESCRIPTION=
ActionCarryForward.LONG_DESCRIPTION=
ActionCarryForward.NAME=
ActionFlagAtTerm.SHORT_DESCRIPTION=
ActionFlagAtTerm.LONG_DESCRIPTION=
ActionFlagAtTerm.NAME=
ActionRepairStartDate.SHORT_DESCRIPTION=
ActionRepairStartDate.LONG_DESCRIPTION=
ActionRepairStartDate.NAME=
ActionPrintBill.SHORT_DESCRIPTION=\u79DF\u8CC3\u5408\u540C\u5957\u6253
ActionPrintBill.LONG_DESCRIPTION=\u79DF\u8CC3\u5408\u540C\u5957\u6253
ActionPrintBill.NAME=\u79DF\u8CC3\u5408\u540C\u5957\u6253
ActionPrintPreviewBill.SHORT_DESCRIPTION=\u79DF\u8CC3\u5408\u540C\u5957\u6253\u9810\u89BD
ActionPrintPreviewBill.LONG_DESCRIPTION=\u79DF\u8CC3\u5408\u540C\u5957\u6253\u9810\u89BD
ActionPrintPreviewBill.NAME=\u79DF\u8CC3\u5408\u540C\u5957\u6253\u9810\u89BD
ActionPriceChange.SHORT_DESCRIPTION=
ActionPriceChange.LONG_DESCRIPTION=
ActionPriceChange.NAME=
ActionCustomerChangeName.SHORT_DESCRIPTION=
ActionCustomerChangeName.LONG_DESCRIPTION=
ActionCustomerChangeName.NAME=
ActionImportSql.SHORT_DESCRIPTION=
ActionImportSql.LONG_DESCRIPTION=
ActionImportSql.NAME=
ActionImport.SHORT_DESCRIPTION=
ActionImport.LONG_DESCRIPTION=
ActionImport.NAME=