this.title=\u5176\u4ED6\u5408\u540C
contCompany.boundLabelText=\u516C\u53F8
contRoom.boundLabelText=\u623F\u9593\u4FE1\u606F
contCustomer.boundLabelText=\u5BA2\u6236\u4FE1\u606F
contTenancy.boundLabelText=\u79DF\u8CC3\u5408\u540C
contSellProject.boundLabelText=\u71DF\u92B7\u9805\u76EE
contNumber.boundLabelText=\u55AE\u64DA\u7DE8\u865F
contSaleMan.boundLabelText=\u7F6E\u696D\u9867\u554F
contEntry.constraints=\u6B3E\u9805
kdtEntry.moneyDefine=\u6B3E\u9805\u540D\u7A31
kdtEntry.amount=\u6536\u53D6\u91D1\u984D\uFF08\u542B\u7A05\uFF09
kdtEntry.totalAmount=\u6536\u53D6\u7E3D\u984D
kdtEntry.rate=\u7A05\u7387%
kdtEntry.amountNoTax=\u6536\u53D6\u91D1\u984D\uFF08\u4E0D\u542B\u7A05\uFF09
kdtEntry.price=\u55AE\u50F9
kdtEntry.workload=\u9762\u7A4D/\u91CF
kdtEntry.description=\u5099\u8A3B
kdtEntry.formatXml=<?xml version\="1.0" encoding\="UTF-8"?><DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles><c\:Style id\="sCol2"><c\:Protection locked\="true" /></c\:Style><c\:Style id\="sCol3"><c\:Protection locked\="true" /></c\:Style><c\:Style id\="sCol4"><c\:Protection locked\="true" /></c\:Style></Styles><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="15" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100"><t\:ColumnGroup><t\:Column t\:key\="moneyDefine" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="true" t\:index\="-1" /><t\:Column t\:key\="amount" t\:width\="120" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="true" t\:index\="5" /><t\:Column t\:key\="totalAmount" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="2" t\:styleID\="sCol2" /><t\:Column t\:key\="rate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="3" t\:styleID\="sCol3" /><t\:Column t\:key\="amountNoTax" t\:width\="120" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="4" t\:styleID\="sCol4" /><t\:Column t\:key\="price" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="5" /><t\:Column t\:key\="workload" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="6" /><t\:Column t\:key\="description" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" t\:index\="7" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header1" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>\u6B3E\u9805\u540D\u7A31</t\:Cell><t\:Cell>\u6536\u53D6\u91D1\u984D\uFF08\u542B\u7A05\uFF09</t\:Cell><t\:Cell>\u6536\u53D6\u7E3D\u984D</t\:Cell><t\:Cell>\u7A05\u7387%</t\:Cell><t\:Cell>\u6536\u53D6\u91D1\u984D\uFF08\u4E0D\u542B\u7A05\uFF09</t\:Cell><t\:Cell>\u55AE\u50F9</t\:Cell><t\:Cell>\u9762\u7A4D/\u91CF</t\:Cell><t\:Cell>\u5099\u8A3B</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot>
tblPayList.constraints=\u6536\u6B3E\u660E\u7D30
contName.boundLabelText=\u55AE\u64DA\u540D\u7A31
contDescription.boundLabelText=\u5099\u8A3B
contCreator.boundLabelText=\u5275\u5EFA\u8005
contAuditor.boundLabelText=\u5BE9\u6838\u4EBA
contCreateTime.boundLabelText=\u5275\u5EFA\u6642\u9593
contAuditTime.boundLabelText=\u5BE9\u6279\u6642\u9593
contStartDate.boundLabelText=\u958B\u59CB\u65E5\u671F
contEndDate.boundLabelText=\u7D50\u675F\u65E5\u671F
contLeaseTime.boundLabelText=\u6536\u53D6\u9031\u671F(\u6708)
contContractNo.boundLabelText=\u624B\u5DE5\u5408\u540C\u865F
contDept.boundLabelText=\u90E8\u9580
contDes.boundLabelText=\u4FDD\u8B49\u91D1\u4FE1\u606F
contType.boundLabelText=\u5408\u540C\u985E\u578B
cbType.items=[Enum]com.kingdee.eas.fdc.tenancy.OtherBillTypeEnum
adjustTaxRate.text=\u7A05\u7387\u8ABF\u6574
ActionSubmit.SHORT_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.LONG_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.NAME=\u63D0\u4EA4
ActionAdjustTaxRate.SHORT_DESCRIPTION=
ActionAdjustTaxRate.LONG_DESCRIPTION=
ActionAdjustTaxRate.NAME=