this.title=\u661F\u701A\u623F\u9593
contNumber.boundLabelText=\u7DE8\u78BC
contName.boundLabelText=\u540D\u7A31
contArea.boundLabelText=\u9762\u7A4D
contIsSale.boundLabelText=\u662F\u5426\u5DF2\u552E
cbIsSale.items=[Enum]com.kingdee.eas.fdc.contract.app.YesOrNoEnum
ActionALine.SHORT_DESCRIPTION=
ActionALine.LONG_DESCRIPTION=
ActionALine.NAME=
ActionILine.SHORT_DESCRIPTION=
ActionILine.LONG_DESCRIPTION=
ActionILine.NAME=
ActionRLine.SHORT_DESCRIPTION=
ActionRLine.LONG_DESCRIPTION=
ActionRLine.NAME=