this.title=\u5176\u4ED6\u5408\u540C\u5E8F\u65F6\u7C3F\u8FC7\u6EE4
contRoom.boundLabelText=\u623F\u95F4
contCustomer.boundLabelText=\u5BA2\u6237
contStartFromDate.boundLabelText=\u8D77\u59CB\u65E5
contStartToDate.boundLabelText=\u81F3
contEndFromDate.boundLabelText=\u7EC8\u6B62\u65E5
contEndToDate.boundLabelText=\u81F3
contMoneyDefine.boundLabelText=\u6B3E\u9879\u7C7B\u578B