this.title=\u5176\u4ED6\u5408\u540C\u5E8F\u6642\u7C3F\u904E\u6FFE
contRoom.boundLabelText=\u623F\u9593
contCustomer.boundLabelText=\u5BA2\u6236
contStartFromDate.boundLabelText=\u8D77\u59CB\u65E5
contStartToDate.boundLabelText=\u81F3
contEndFromDate.boundLabelText=\u7D42\u6B62\u65E5
contEndToDate.boundLabelText=\u81F3
contMoneyDefine.boundLabelText=\u6B3E\u9805\u985E\u578B