this.title=\u8BA4\u79DF\u5355
panelTotal.constraints=\u6C47\u603B\u4FE1\u606F
contDescription.boundLabelText=\u5907\u6CE8\:
kDPanel2.constraints=\u5408\u540C\u4FE1\u606F
contCreator.boundLabelText=\u5236\u5355\u4EBA
contCreateTime.boundLabelText=\u5236\u5355\u65E5\u671F\:
tblRoom.column1=\u9879\u76EE
tblRoom.column2=\u697C\u680B
tblRoom.column3=\u5355\u5143
tblRoom.column4=\u623F\u95F4
tblRoom.column5=\u697C\u5C42
tblRoom.column6=\u6807\u51C6\u79DF\u91D1
tblRoom.column7=\u6807\u51C6\u5355\u4EF7
tblRoom.column8=\u6210\u4EA4\u79DF\u91D1
tblRoom.column9=\u6210\u4EA4\u5355\u4EF7
tblRoom.column10=\u5EFA\u7B51\u9762\u79EF
tblRoom.column11=\u5957\u5185\u9762\u79EF
tblRoom.column12=\u88C5\u4FEE\u60C5\u51B5
tblRoom.column13=\u6237\u578B
tblRoom.column14=\u671D\u5411
tblRoom.column15=\u5230\u671F\u6807\u8BB0
tblRoom.formatXml=<?xml version\="1.0" encoding\="UTF-8"?> <DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles /><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="15" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100"><t\:ColumnGroup><t\:Column t\:key\="column1" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column2" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column3" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column4" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column5" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column6" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column7" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column8" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column9" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column10" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column11" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column12" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column13" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column14" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column15" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header1" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>\u9879\u76EE</t\:Cell><t\:Cell>\u697C\u680B</t\:Cell><t\:Cell>\u5355\u5143</t\:Cell><t\:Cell>\u623F\u95F4</t\:Cell><t\:Cell>\u697C\u5C42</t\:Cell><t\:Cell>\u6807\u51C6\u79DF\u91D1</t\:Cell><t\:Cell>\u6807\u51C6\u5355\u4EF7</t\:Cell><t\:Cell>\u6210\u4EA4\u79DF\u91D1</t\:Cell><t\:Cell>\u6210\u4EA4\u5355\u4EF7</t\:Cell><t\:Cell>\u5EFA\u7B51\u9762\u79EF</t\:Cell><t\:Cell>\u5957\u5185\u9762\u79EF</t\:Cell><t\:Cell>\u88C5\u4FEE\u60C5\u51B5</t\:Cell><t\:Cell>\u6237\u578B</t\:Cell><t\:Cell>\u671D\u5411</t\:Cell><t\:Cell>\u5230\u671F\u6807\u8BB0</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot> 
contTenancyType.boundLabelText=\u5408\u540C\u7C7B\u578B
contOldContract.boundLabelText=\u6539\u7EED\u539F\u5408\u540C
contChangeDes.boundLabelText=\u6539\u7EED\u79DF\u8BF4\u660E
contContractNo.boundLabelText=\u5408\u540C\u540D\u79F0
contname.boundLabelText=\u5408\u540C\u540D\u79F0
contNumber.boundLabelText=\u5408\u540C\u7F16\u53F7
contTotalRoomStandardRent.boundLabelText=\u603B\u6807\u51C6\u79DF\u91D1
contTotalRoomDealRent.boundLabelText=\u603B\u6807\u51C6\u79DF\u91D1
contTotalBuildingArea.boundLabelText=\u603B\u5EFA\u7B51\u9762\u79EF
btnAddRoom.text=\u6DFB\u52A0
btnRemoveRoom.text=\u5220\u9664
tblCustomer.propertyPercent=\u51FA\u79DF\u6BD4\u4F8B(%)
tblCustomer.customer=\u5BA2\u6237
tblCustomer.postalcode=\u90AE\u7F16
tblCustomer.phone=\u8054\u7CFB\u7535\u8BDD
tblCustomer.certificateName=\u8BC1\u4EF6\u540D\u79F0
tblCustomer.certificateNumber=\u8BC1\u4EF6\u53F7\u7801
tblCustomer.mailAddress=\u901A\u4FE1\u5730\u5740
tblCustomer.bookDate=\u767B\u8BB0\u65E5\u671F
tblCustomer.des=\u5907\u6CE8
tblCustomer.formatXml=<?xml version\="1.0" encoding\="UTF-8"?> <DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles /><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="15" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100"><t\:ColumnGroup><t\:Column t\:key\="propertyPercent" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="customer" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="postalcode" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="phone" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="certificateName" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="certificateNumber" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="mailAddress" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="bookDate" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="des" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header1" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>\u51FA\u79DF\u6BD4\u4F8B(%)</t\:Cell><t\:Cell>\u5BA2\u6237</t\:Cell><t\:Cell>\u90AE\u7F16</t\:Cell><t\:Cell>\u8054\u7CFB\u7535\u8BDD</t\:Cell><t\:Cell>\u8BC1\u4EF6\u540D\u79F0</t\:Cell><t\:Cell>\u8BC1\u4EF6\u53F7\u7801</t\:Cell><t\:Cell>\u901A\u4FE1\u5730\u5740</t\:Cell><t\:Cell>\u767B\u8BB0\u65E5\u671F</t\:Cell><t\:Cell>\u5907\u6CE8</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot> 
contFirstLeaseType.boundLabelText=\u8BA1\u79DF\u65E5
contEndDate.boundLabelText=\u7ED3\u675F\u65E5\u671F
contLeaseTime.boundLabelText=\u8BA1\u79DF\u671F\u95F4\u957F\u5EA6(\u6708)
contLeaseCount.boundLabelText=\u5408\u540C\u79DF\u671F
contStartDate.boundLabelText=\u5F00\u59CB\u65E5\u671F
btnRemoveCustomer.text=\u5220\u9664
btnNewCustomer.text=\u65B0\u589E\u5BA2\u6237
btnAddCustomer.text=\u6DFB\u52A0
panelContractInfo.constraints=\u5408\u540C\u4FE1\u606F
contSpecialClause.boundLabelText=\u7279\u6B8A\u6761\u6B3E
conttenRevBank.boundLabelText=\u6258\u6536\u94F6\u884C
contStandardTotalRent.boundLabelText=\u6807\u51C6\u79DF\u91D1
contDeliveryRoomDate.boundLabelText=\u7EA6\u5B9A\u4EA4\u623F\u65E5\u671F
contDealTotalRent.boundLabelText=\u6210\u4EA4\u79DF\u91D1
contDepositAmount.boundLabelText=\u62BC\u91D1
contfirstTermTenAmo.boundLabelText=\u9996\u4ED8\u79DF\u91D1
contTenancyAdviser.boundLabelText=\u79DF\u8D41\u987E\u95EE
panelRentSet.constraints=\u79DF\u91D1\u8BBE\u7F6E
panelPayList.constraints=\u6536\u6B3E\u660E\u7EC6
panelProperty.constraints=\u7269\u4E1A
panelAgency.constraints=\u4EE3\u7406\u8D44\u6599
contAgency.boundLabelText=\u4E2D\u4ECB\u516C\u53F8
pnlOtherPayList.constraints=\u5176\u4ED6\u5E94\u6536
panelLiquidated.constraints=\u8FDD\u7EA6\u91D1\u8BA1\u7B97\u65B9\u6848\u8BBE\u7F6E
kDPaneLongContract.constraints=\u957F\u79DF\u5408\u540C\u8BBE\u7F6E
panelCommissionSetting.constraints=\u8425\u4E1A\u63D0\u6210\u8BBE\u7F6E
kDLabelContainer1.boundLabelText=\u5408\u540C\u7F16\u53F7
kDLabelContainer2.boundLabelText=\u6539\u7EED\u539F\u5408\u540C
kDLabelContainer3.boundLabelText=\u5408\u540C\u7F16\u53F7
kDLabelContainer4.boundLabelText=\u5408\u540C\u7F16\u53F7
kDLabelContainer5.boundLabelText=\u6539\u7EED\u539F\u5408\u540C
kDLabelContainer6.boundLabelText=\u5408\u540C\u7C7B\u578B
panelXHTenancyBill.constraints=\u661F\u701A\u5408\u540C
panelAttachRes.constraints=\u914D\u5957\u8D44\u6E90
tblAttachRes.column1=\u9879\u76EE
tblAttachRes.column2=\u697C\u680B
tblAttachRes.column3=\u914D\u5957\u8D44\u6E90\u540D\u79F0
tblAttachRes.column4=\u914D\u5957\u8D44\u6E90\u8BF4\u660E
tblAttachRes.column5=\u6807\u51C6\u79DF\u91D1
tblAttachRes.column6=\u6807\u51C6\u5355\u4EF7
tblAttachRes.column7=\u6210\u4EA4\u79DF\u91D1
tblAttachRes.column8=\u6210\u4EA4\u5355\u4EF7
tblAttachRes.column9=\u5230\u671F\u6807\u8BB0
tblAttachRes.formatXml=<?xml version\="1.0" encoding\="UTF-8"?> <DocRoot xmlns\:c\="http\://www.kingdee.com/Common" xmlns\:f\="http\://www.kingdee.com/Form" xmlns\:t\="http\://www.kingdee.com/Table" xmlns\:xsi\="http\://www.w3.org/2001/XMLSchema-instance" xsi\:schemaLocation\="http\://www.kingdee.com/KDF KDFSchema.xsd" version\="0.0"><Styles /><Table id\="KDTable"><t\:Sheet name\="sheet1"><t\:Table t\:selectMode\="15" t\:mergeMode\="0" t\:dataRequestMode\="0" t\:pageRowCount\="100"><t\:ColumnGroup><t\:Column t\:key\="column1" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column2" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column3" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column4" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column5" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column6" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column7" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column8" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /><t\:Column t\:key\="column9" t\:width\="-1" t\:mergeable\="true" t\:resizeable\="true" t\:moveable\="true" t\:group\="false" t\:required\="false" /></t\:ColumnGroup><t\:Head><t\:Row t\:name\="header" t\:height\="-1" t\:mergeable\="true" t\:resizeable\="true"><t\:Cell>\u9879\u76EE</t\:Cell><t\:Cell>\u697C\u680B</t\:Cell><t\:Cell>\u914D\u5957\u8D44\u6E90\u540D\u79F0</t\:Cell><t\:Cell>\u914D\u5957\u8D44\u6E90\u8BF4\u660E</t\:Cell><t\:Cell>\u6807\u51C6\u79DF\u91D1</t\:Cell><t\:Cell>\u6807\u51C6\u5355\u4EF7</t\:Cell><t\:Cell>\u6210\u4EA4\u79DF\u91D1</t\:Cell><t\:Cell>\u6210\u4EA4\u5355\u4EF7</t\:Cell><t\:Cell>\u5230\u671F\u6807\u8BB0</t\:Cell></t\:Row></t\:Head></t\:Table><t\:SheetOptions><t\:MergeBlocks><t\:Head /></t\:MergeBlocks></t\:SheetOptions></t\:Sheet></Table></DocRoot> 
btnAddAttachRes.text=\u6DFB\u52A0
btnRemoveAttachRes.text=\u5220\u9664
contTotalAttachResStandardRent.boundLabelText=\u603B\u6807\u51C6\u79DF\u91D1
contTotalAttachResDealRent.boundLabelText=\u603B\u6807\u51C6\u79DF\u91D1
ActionSubmit.SHORT_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.LONG_DESCRIPTION=\u63D0\u4EA4
ActionSubmit.NAME=\u63D0\u4EA4
ActionPrint.SHORT_DESCRIPTION=\u6253\u5370
ActionPrint.LONG_DESCRIPTION=\u6253\u5370
ActionPrint.NAME=\u6253\u5370
ActionPrintPreview.SHORT_DESCRIPTION=\u6253\u5370\u9884\u89C8
ActionPrintPreview.LONG_DESCRIPTION=\u6253\u5370\u9884\u89C8
ActionPrintPreview.NAME=\u6253\u5370\u9884\u89C8
ActionAddNew.SHORT_DESCRIPTION=
ActionAddNew.LONG_DESCRIPTION=
ActionAddNew.NAME=\u65B0\u589E
ActionCarryForward.SHORT_DESCRIPTION=
ActionCarryForward.LONG_DESCRIPTION=
ActionCarryForward.NAME=
ActionAddCollectProtocol.SHORT_DESCRIPTION=
ActionAddCollectProtocol.LONG_DESCRIPTION=
ActionAddCollectProtocol.NAME=
ActionAddRoom.SHORT_DESCRIPTION=
ActionAddRoom.LONG_DESCRIPTION=
ActionAddRoom.NAME=
ActionRemoveRoom.SHORT_DESCRIPTION=
ActionRemoveRoom.LONG_DESCRIPTION=
ActionRemoveRoom.NAME=
ActionAddCustomer.SHORT_DESCRIPTION=
ActionAddCustomer.LONG_DESCRIPTION=
ActionAddCustomer.NAME=
ActionRemoveCustomer.SHORT_DESCRIPTION=
ActionRemoveCustomer.LONG_DESCRIPTION=
ActionRemoveCustomer.NAME=
ActionAdust.SHORT_DESCRIPTION=
ActionAdust.LONG_DESCRIPTION=
ActionAdust.NAME=
ActionSelectTenPrice.SHORT_DESCRIPTION=
ActionSelectTenPrice.LONG_DESCRIPTION=
ActionSelectTenPrice.NAME=
ActionUpdateTenPrice.SHORT_DESCRIPTION=
ActionUpdateTenPrice.LONG_DESCRIPTION=
ActionUpdateTenPrice.NAME=
ActionUpdateXHTenancyBill.SHORT_DESCRIPTION=
ActionUpdateXHTenancyBill.LONG_DESCRIPTION=
ActionUpdateXHTenancyBill.NAME=
ActionALine.SHORT_DESCRIPTION=
ActionALine.LONG_DESCRIPTION=
ActionALine.NAME=
ActionRLine.SHORT_DESCRIPTION=
ActionRLine.LONG_DESCRIPTION=
ActionRLine.NAME=