this.title=
contStartFromDate.boundLabelText=\u521B\u5EFA\u65F6\u95F4
contStartToDate.boundLabelText=\u521B\u5EFA\u65F6\u95F4
contEndFromDate.boundLabelText=\u521B\u5EFA\u65F6\u95F4
contEndToDate.boundLabelText=\u521B\u5EFA\u65F6\u95F4