this.title=\u661F\u701A\u5BA2\u6237
contNumber.boundLabelText=\u7F16\u7801
contName.boundLabelText=\u540D\u79F0
ActionALine.SHORT_DESCRIPTION=
ActionALine.LONG_DESCRIPTION=
ActionALine.NAME=
ActionILine.SHORT_DESCRIPTION=
ActionILine.LONG_DESCRIPTION=
ActionILine.NAME=
ActionRLine.SHORT_DESCRIPTION=
ActionRLine.LONG_DESCRIPTION=
ActionRLine.NAME=